//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groceries
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAddress
    {
        public string AddressID { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Unit { get; set; }
        public string Postcode { get; set; }
        public string CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
